#Arena Border Addon for MBedwars by dejwideek

#Don't change this!
config-version: 1

#Permissions
Permissions:
  Reload: "bw.arenaborder.reload"

#Messages
Messages:
  #Available placeholder: %permission%
  No-Permission: "&cYou must have permission &4%permission% &cto do this!"

  Reloaded: "&eSuccessfully reloaded configuration file!"

#Border configuration
Border:
  Default:
    Center-Location:
      X: 0.0
      Z: 0.0
    Size: 300.0

  #You can add sections for arenas, by default
  #It's disabled but u can remove # and [] and it should work.
  #Just replace arena1 to your arena name and copy if u need more
  #configurations
  Arenas: []
#    arena1:
#      Center-Location:
#        X: 0.0
#        Z: 0.0
#      Size: 250.0

#Disabled arenas from border
Disabled-Arenas:
  - disabledArena1
  - disabledArena2