#Arena Border Addon for MBedwars by dejwideek

#Hex color: <SOLID:(hex without #)>
#Example: "<SOLID:fdfdfd>hex color"

#Hex gradient color:
#- start variable: <GRADIENT:(hex without #)>
#- end variable: </GRADIENT:(hex without #)>
#Example: "<GRADIENT:000000>gradient</GRADIENT:ffffff>"

#Hex rainbow color:
#- start variable: <RAINBOW(saturation value)>
#- end variable: </RAINBOW>
#Smaller value: darker
#Higher value: brighter
#Example: "<RAINBOW1>rainbow</RAINBOW>"

#This features works only on 1.16+ version

#Don't change this!
config-version: 1

#Permissions
Permissions:
  Reload: "bw.arenaborder.reload"

#Messages
Messages:
  #Available placeholder: %permission%
  No-Permission: "&cYou must have permission &4%permission% &cto do this!"

  Reloaded: "&eSuccessfully reloaded configuration file!"

#Border configuration
Border:
  Default:
    Center-Location:
      X: 0.0
      Z: 0.0
    Size: 300.0

  #You can add sections for arenas, by default
  #It's disabled but u can remove # and [] and it should work.
  #Just replace arena1 to your arena name and copy if u need more
  #configurations
  Arenas: []
#    arena1:
#      Center-Location:
#        X: 0.0
#        Z: 0.0
#      Size: 250.0

#Disabled arenas from border
Disabled-Arenas:
  - disabledArena1
  - disabledArena2