name: MBedwarsArenaBorderAddon
version: 1.0.1
authors: [dejwideek]
depend: [MBedwars]
main: pl.dejwideek.mbwarenaborder.ArenaBorderAddon
commands:
  arenaborderreload:
    aliases:
      - abreload
    description: Reload config file